-- ÖZEL REKLAM YÖNETİMİ — Supabase SQL Editor'da bir kez çalıştırın
-- (Supabase Dashboard → SQL Editor → New query → yapıştır → Run)

create table if not exists public.reklamlar (
  id                bigint generated by default as identity primary key,
  baslik            text        not null default '',
  gorsel_url        text        not null,
  link_url          text        not null default '',
  konum             text        not null check (konum in ('video', 'sidebar')),
  aktif             boolean     not null default true,
  baslangic_tarihi  timestamptz,
  bitis_tarihi      timestamptz,
  siralama          integer     not null default 0,
  tiklanma          integer     not null default 0,
  created_at        timestamptz not null default now()
);

create index if not exists reklamlar_konum_aktif_idx on public.reklamlar (konum, aktif);

-- RLS: herkes yalnızca aktif reklamları okuyabilir; yazma işlemleri servis anahtarı (admin API) ile yapılır
alter table public.reklamlar enable row level security;

drop policy if exists "reklamlar_aktif_okuma" on public.reklamlar;
create policy "reklamlar_aktif_okuma"
  on public.reklamlar for select
  using (aktif = true);
