-- Kovan Portal, Ümraniye Sanayi Sitesi kodunu temel alıyor: onun tabloları Kovan veritabanına kuruluyor.
-- Yazma işlemleri sunucuda service role ile yapılır; aşağıdaki kurallar sadece herkese açık okumayı belirler.
-- Yöneticiler: sadettinbal@gmail.com, mustafabal93@gmail.com (kodda ADMIN_EMAILS ile aynı)

-- 1) Kovan'ın eski üye tablosu kenara alınır (silinmez); onu dolduran tetik kaldırılır
drop trigger if exists yeni_uye_kaydi on auth.users;
alter table if exists public.uyeler rename to uyeler_eski;

-- 2) Firmalar
create table if not exists public.firmalar (
  id integer generated by default as identity primary key,
  ad text not null,
  sahip text,
  sektor text,
  sanayi_sitesi text,
  adres text,
  telefon text,
  mobil_telefon text,
  hizmetler text[] not null default '{}',
  aciklama text,
  ozel_firma boolean not null default false,
  fotograf_url text,
  detay_fotograflar text[],
  onay_durumu text not null default 'onaylandi' check (onay_durumu in ('beklemede', 'onaylandi', 'reddedildi')),
  web_sitesi text,
  instagram text,
  facebook text,
  twitter text,
  youtube text,
  linkedin text,
  tiktok text,
  kullanici_email text,
  yeniden_gonderildi boolean,
  bekleyen_degisiklikler jsonb,
  guncelleme_talep_tarihi timestamptz,
  hedef_sayfa integer,
  -- Türkiye geneli (Kovan): konum ve kategori
  il_adi text,
  ilce_adi text,
  site_id integer references public.sanayi_siteleri(id) on delete set null,
  mahalle_id bigint,
  sokak_id integer,
  alt_kategori_id integer references public.alt_kategoriler(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz
);
create index if not exists firmalar_sanayi_sitesi_idx on public.firmalar(sanayi_sitesi);
create index if not exists firmalar_sektor_idx on public.firmalar(sektor);
create index if not exists firmalar_onay_durumu_idx on public.firmalar(onay_durumu);
create index if not exists firmalar_kullanici_email_idx on public.firmalar(kullanici_email);
create index if not exists firmalar_site_id_idx on public.firmalar(site_id);

alter table public.firmalar enable row level security;
create policy "onayli firmalar herkese acik, sahibi ve yonetici hepsini gorur" on public.firmalar
  for select using (
    onay_durumu = 'onaylandi'
    or kullanici_email = (select auth.jwt() ->> 'email')
    or (select auth.jwt() ->> 'email') in ('sadettinbal@gmail.com', 'mustafabal93@gmail.com')
  );

-- 3) Yorum ve puanlar (her kullanıcı bir firmaya bir kez)
create table if not exists public.yorumlar (
  id bigint generated by default as identity primary key,
  firma_id integer not null references public.firmalar(id) on delete cascade,
  kullanici_email text not null,
  kullanici_ad text not null default '',
  yorum text not null,
  puan integer not null check (puan between 1 and 5),
  created_at timestamptz not null default now()
);
create index if not exists yorumlar_firma_id_idx on public.yorumlar(firma_id);
create unique index if not exists yorumlar_unique_user_firma on public.yorumlar(firma_id, kullanici_email);

alter table public.yorumlar enable row level security;
create policy "yorumlar herkese acik" on public.yorumlar for select using (true);

-- 4) İlanlar
create table if not exists public.ilanlar (
  id bigint generated by default as identity primary key,
  baslik text not null,
  aciklama text not null,
  fiyat text,
  kategori text not null,
  telefon text not null,
  ilan_veren_ad text not null,
  ilan_veren_email text,
  fotograflar text[] not null default '{}',
  onay_durumu text not null default 'beklemede' check (onay_durumu in ('beklemede', 'onaylandi', 'reddedildi')),
  created_at timestamptz not null default now()
);
create index if not exists ilanlar_onay_durumu_idx on public.ilanlar(onay_durumu);
create index if not exists ilanlar_created_at_idx on public.ilanlar(created_at desc);

alter table public.ilanlar enable row level security;
create policy "onayli ilanlar herkese acik, sahibi ve yonetici hepsini gorur" on public.ilanlar
  for select using (
    onay_durumu = 'onaylandi'
    or ilan_veren_email = (select auth.jwt() ->> 'email')
    or (select auth.jwt() ->> 'email') in ('sadettinbal@gmail.com', 'mustafabal93@gmail.com')
  );

-- 5) Ziyaret istatistikleri (sadece sunucu okur/yazar)
create table if not exists public.ziyaretler (
  id bigint generated by default as identity primary key,
  sayfa text not null,
  firma_id integer references public.firmalar(id) on delete set null,
  referrer text,
  cihaz text,
  ip text,
  bolge text,
  created_at timestamptz not null default now()
);
create index if not exists ziyaretler_created_at_idx on public.ziyaretler(created_at);
create index if not exists ziyaretler_firma_id_idx on public.ziyaretler(firma_id);
alter table public.ziyaretler enable row level security;

-- 6) Reklamlar (herkes sadece aktif reklamları okur)
create table if not exists public.reklamlar (
  id bigint generated by default as identity primary key,
  baslik text not null default '',
  gorsel_url text not null,
  link_url text not null default '',
  konum text not null check (konum in ('video', 'sidebar', 'popup')),
  kategori text,
  aktif boolean not null default true,
  baslangic_tarihi timestamptz,
  bitis_tarihi timestamptz,
  siralama integer not null default 0,
  tiklanma integer not null default 0,
  created_at timestamptz not null default now()
);
create index if not exists reklamlar_konum_aktif_idx on public.reklamlar(konum, aktif);
alter table public.reklamlar enable row level security;
create policy "aktif reklamlar herkese acik" on public.reklamlar for select using (aktif = true);

-- 7) Site içerikleri (örn. Site Kullanımı metni; sunucu okur/yazar)
create table if not exists public.site_icerikleri (
  anahtar text primary key,
  icerik text not null default '',
  guncelleme_tarihi timestamptz not null default now()
);
alter table public.site_icerikleri enable row level security;

-- 8) Google ile giriş yapan kullanıcılar (sunucu yazar; kullanıcı sadece kendi kaydını görür)
create table if not exists public.users (
  id bigint generated by default as identity primary key,
  google_id text not null unique,
  email text not null,
  name text not null,
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz
);
create index if not exists users_email_idx on public.users(email);
alter table public.users enable row level security;
create policy "kullanici kendi kaydini gorur" on public.users
  for select to authenticated using ((select auth.uid())::text = google_id);

-- 9) "Üye Ol" başvuru formu (şifresiz başvuru; sunucu yazar)
create table if not exists public.uyeler (
  id bigint generated by default as identity primary key,
  isim text not null,
  soyisim text not null,
  sabit_telefon text,
  mobil_telefon text,
  email text not null,
  created_at timestamptz not null default now()
);
alter table public.uyeler enable row level security;

-- 10) Dosya depoları (herkese açık okunur; yükleme sunucuda service role ile).
-- Boyut/tür sınırı yok: firma-fotograflari reklam videolarını da tutuyor
insert into storage.buckets (id, name, public)
values
  ('firma-fotograflari', 'firma-fotograflari', true),
  ('ilan-fotograflari', 'ilan-fotograflari', true)
on conflict (id) do nothing;

notify pgrst, 'reload schema';
