-- Kod dosyalarındaki kategorilerin firma_kategorileri tablosuna aktarımı (86 ana, 127 alt). Sadece ekleme yapar.
insert into public.firma_kategorileri (ad, tip, sira) values
('AHŞAP MOBİLYA İMALATI VE AKSESUAR', 'sanayi_sitesi', 1),
('AİRBAG TAMİR FİRMALARI', 'sanayi_sitesi', 2),
('AKÜ İMALATI', 'sanayi_sitesi', 3),
('AMORTİSÖR TAMİRCİLERİ', 'sanayi_sitesi', 4),
('BOBİNAJ VE ELEKTRİK MOTOR TAMİRCİLERİ', 'sanayi_sitesi', 5),
('CİVATA SATAN FİRMALAR', 'sanayi_sitesi', 6),
('CNC KALIP İMALATI', 'sanayi_sitesi', 7),
('CONTACILAR', 'sanayi_sitesi', 8),
('DEMİR DOĞRAMACILAR', 'sanayi_sitesi', 9),
('DİĞER FİRMALAR', 'sanayi_sitesi', 10),
('ELEKTRİK ELEKTRONİK', 'sanayi_sitesi', 11),
('HIRDAVATCILAR', 'sanayi_sitesi', 12),
('KAMYON TAMİRİ', 'sanayi_sitesi', 13),
('KARBÜRATÖRCÜLER', 'sanayi_sitesi', 14),
('KIRTASİYE İMALATI', 'sanayi_sitesi', 15),
('LPG OCAK BAŞLIĞI İMALATI', 'sanayi_sitesi', 16),
('MAKİNA İMALATÇILARI', 'sanayi_sitesi', 17),
('NALBURİYE', 'sanayi_sitesi', 18),
('OTO AKSESUAR MALZEMELERİ SATAN FİRMALAR', 'sanayi_sitesi', 19),
('OTO AKÜ SATAN FİRMALAR', 'sanayi_sitesi', 20),
('OTO ALIM SATIM', 'sanayi_sitesi', 21),
('OTO ANAHTARCILAR', 'sanayi_sitesi', 22),
('OTO BOYACILAR', 'sanayi_sitesi', 23),
('OTO CAM KİLİT TAMİRCİLERİ', 'sanayi_sitesi', 24),
('OTO CAMCILAR', 'sanayi_sitesi', 25),
('OTO DÖŞEMECİLER', 'sanayi_sitesi', 26),
('OTO EKSOZ MUAYNE VE ÖLÇÜM', 'sanayi_sitesi', 27),
('OTO EKSOZ TAMİRCİLERİ', 'sanayi_sitesi', 28),
('OTO EKSPERTİZ FİRMALARI', 'sanayi_sitesi', 29),
('OTO ELEKTRİKÇİLER', 'sanayi_sitesi', 30),
('OTO ELEKTRONİKÇİLER', 'sanayi_sitesi', 31),
('OTO FREN BALATA', 'sanayi_sitesi', 32),
('OTO GAZ SİSTEMLERİ', 'sanayi_sitesi', 33),
('OTO HİDROLİK DİREKSİYON', 'sanayi_sitesi', 34),
('OTO HİDROLİK FİRMALARI', 'sanayi_sitesi', 35),
('OTO KAPORTA TAMİRCİLERİ', 'sanayi_sitesi', 36),
('OTO KLİMA TAMİRCİLERİ', 'sanayi_sitesi', 37),
('OTO LASTİK JANT SERVİSLERİ', 'sanayi_sitesi', 38),
('OTO MAKASÇILAR', 'sanayi_sitesi', 39),
('OTO MEKANİK', 'sanayi_sitesi', 40),
('OTO MOTOR TAMİRCİLERİ', 'sanayi_sitesi', 41),
('OTO RADYÖTÖRCÜLER', 'sanayi_sitesi', 42),
('OTO ROT BALANS TAMİRCİLERİ', 'sanayi_sitesi', 43),
('OTO ŞANZUMAN TAMİRCİLERİ', 'sanayi_sitesi', 44),
('OTO TANPON FİBERGLAS TAMİRİ', 'sanayi_sitesi', 45),
('OTO YEDEK PARÇA MALZEMELERİ SATAN FİRMALAR', 'sanayi_sitesi', 46),
('OTO YIKAMA KUAFÖR', 'sanayi_sitesi', 47),
('PLS.ÇİLERPLS İMLTPLS ENJEKSİYON VE KALIPÇILAR', 'sanayi_sitesi', 48),
('POMPA VE ENJEKTÖR TAMİRCİLERİ', 'sanayi_sitesi', 49),
('REKTİFİYECİLER', 'sanayi_sitesi', 50),
('RULMAN SATAN FİRMALAR', 'sanayi_sitesi', 51),
('SANAYİ MAKİNA ALIM SATIMI', 'sanayi_sitesi', 52),
('SOSYAL TESİSLER(LOKANTA,ÇAY OCAĞI,BÜFE)', 'sanayi_sitesi', 53),
('SPOR ALETLERİ İMALATI', 'sanayi_sitesi', 54),
('ŞAFT BALANS', 'sanayi_sitesi', 55),
('ŞAFT KOVAN TORNACILARI', 'sanayi_sitesi', 56),
('TORNACILAR,KAYNAKÇILAR,PRESÇİLER', 'sanayi_sitesi', 57),
('TURBO BAKIM', 'sanayi_sitesi', 58),
('ÖZEL SERVİSLER', 'sanayi_sitesi', 59),
('MOTOR MEKANİK', 'sanayi_sitesi', 60),
('OTO KAPORTA BOYA', 'sanayi_sitesi', 61),
('YEME İÇME', 'sanayi_disi', 1),
('MARKET & GIDA', 'sanayi_disi', 2),
('GİYİM & AKSESUAR', 'sanayi_disi', 3),
('SAĞLIK & HİZMETLER', 'sanayi_disi', 4),
('EĞİTİM & KÜLTÜR', 'sanayi_disi', 5),
('GÜZELLİK & BAKIM', 'sanayi_disi', 6),
('İNŞAAT & EMLAK', 'sanayi_disi', 7),
('TEKNİK HİZMETLER', 'sanayi_disi', 8),
('DANIŞMANLIK & HİZMET', 'sanayi_disi', 9),
('ULAŞIM & LOJİSTİK', 'sanayi_disi', 10),
('TEMİZLİK & PEYZAJ', 'sanayi_disi', 11),
('DİJİTAL & MEDYA', 'sanayi_disi', 12),
('DİĞER', 'sanayi_disi', 13),
('SAĞLIK', 'kurumsal', 1),
('EĞİTİM', 'kurumsal', 2),
('FİNANS', 'kurumsal', 3),
('İNŞAAT & GAYRİMENKUL', 'kurumsal', 4),
('TEKNOLOJİ', 'kurumsal', 5),
('OTOMOTİV', 'kurumsal', 6),
('TURİZM & KONAKLAMA', 'kurumsal', 7),
('GIDA & İÇECEK', 'kurumsal', 8),
('LOJİSTİK & NAKLİYE', 'kurumsal', 9),
('MEDYA & İLETİŞİM', 'kurumsal', 10),
('ENERJİ', 'kurumsal', 11),
('HUKUK & DANIŞMANLIK', 'kurumsal', 12);

insert into public.firma_kategorileri (ad, tip, ust_kategori_id, sira)
select v.alt, v.tip, a.id, v.sira
from (values
('YEME İÇME', 'sanayi_disi', 'Kafe & Restoran', 1),
('YEME İÇME', 'sanayi_disi', 'Fırın & Pastane', 2),
('YEME İÇME', 'sanayi_disi', 'Yemek Servisi & Catering', 3),
('MARKET & GIDA', 'sanayi_disi', 'Market & Bakkal', 1),
('MARKET & GIDA', 'sanayi_disi', 'Toptan Gıda', 2),
('MARKET & GIDA', 'sanayi_disi', 'Organik Ürün Satışı', 3),
('GİYİM & AKSESUAR', 'sanayi_disi', 'Giyim & Ayakkabı', 1),
('GİYİM & AKSESUAR', 'sanayi_disi', 'Kuaför & Güzellik', 2),
('SAĞLIK & HİZMETLER', 'sanayi_disi', 'Eczane', 1),
('SAĞLIK & HİZMETLER', 'sanayi_disi', 'Veteriner Hizmetleri', 2),
('SAĞLIK & HİZMETLER', 'sanayi_disi', 'Pet Shop', 3),
('EĞİTİM & KÜLTÜR', 'sanayi_disi', 'Eğitim & Kurslar', 1),
('EĞİTİM & KÜLTÜR', 'sanayi_disi', 'Spor Salonları', 2),
('GÜZELLİK & BAKIM', 'sanayi_disi', 'Güzellik & Estetik', 1),
('GÜZELLİK & BAKIM', 'sanayi_disi', 'Berber & Kuaför', 2),
('GÜZELLİK & BAKIM', 'sanayi_disi', 'Kuru Temizleme', 3),
('İNŞAAT & EMLAK', 'sanayi_disi', 'İnşaat & Yapı Malzemeleri', 1),
('İNŞAAT & EMLAK', 'sanayi_disi', 'Emlak & Gayrimenkul', 2),
('İNŞAAT & EMLAK', 'sanayi_disi', 'Mobilya & Dekorasyon', 3),
('TEKNİK HİZMETLER', 'sanayi_disi', 'Elektrikçi', 1),
('TEKNİK HİZMETLER', 'sanayi_disi', 'Boyacı & Badanacı', 2),
('TEKNİK HİZMETLER', 'sanayi_disi', 'Su Tesisatı', 3),
('TEKNİK HİZMETLER', 'sanayi_disi', 'Klima Servisi', 4),
('TEKNİK HİZMETLER', 'sanayi_disi', 'Kombi Servisi', 5),
('TEKNİK HİZMETLER', 'sanayi_disi', 'Beyaz Eşya Tamiri', 6),
('TEKNİK HİZMETLER', 'sanayi_disi', 'Bilgisayar Tamiri', 7),
('TEKNİK HİZMETLER', 'sanayi_disi', 'Telefon Tamiri', 8),
('TEKNİK HİZMETLER', 'sanayi_disi', 'Cam Balkon', 9),
('TEKNİK HİZMETLER', 'sanayi_disi', 'PVC Kapı Pencere', 10),
('TEKNİK HİZMETLER', 'sanayi_disi', 'Asansör Servisi', 11),
('DANIŞMANLIK & HİZMET', 'sanayi_disi', 'Avukat & Hukuk', 1),
('DANIŞMANLIK & HİZMET', 'sanayi_disi', 'Muhasebe & Mali Müşavirlik', 2),
('DANIŞMANLIK & HİZMET', 'sanayi_disi', 'Sigorta Acentesi', 3),
('ULAŞIM & LOJİSTİK', 'sanayi_disi', 'Taksi & Nakliye', 1),
('ULAŞIM & LOJİSTİK', 'sanayi_disi', 'Güvenlik Sistemleri', 2),
('TEMİZLİK & PEYZAJ', 'sanayi_disi', 'Temizlik Hizmetleri', 1),
('TEMİZLİK & PEYZAJ', 'sanayi_disi', 'Peyzaj & Bahçe', 2),
('DİJİTAL & MEDYA', 'sanayi_disi', 'Dijital Medya & Reklam', 1),
('DİJİTAL & MEDYA', 'sanayi_disi', 'Bilişim & Yazılım', 2),
('DİJİTAL & MEDYA', 'sanayi_disi', 'Fotoğraf & Video', 3),
('DİJİTAL & MEDYA', 'sanayi_disi', 'Organizasyon & Etkinlik', 4),
('DİĞER', 'sanayi_disi', 'Diğer Hizmetler', 1),
('SAĞLIK', 'kurumsal', 'Hastaneler', 1),
('SAĞLIK', 'kurumsal', 'Sağlık Hizmetleri', 2),
('SAĞLIK', 'kurumsal', 'Özel Poliklinikler', 3),
('SAĞLIK', 'kurumsal', 'Tıp Merkezleri', 4),
('SAĞLIK', 'kurumsal', 'Diyaliz Merkezleri', 5),
('SAĞLIK', 'kurumsal', 'Fizik Tedavi ve Rehabilitasyon', 6),
('SAĞLIK', 'kurumsal', 'Ağız ve Diş Sağlığı', 7),
('SAĞLIK', 'kurumsal', 'Görüntüleme Merkezleri', 8),
('SAĞLIK', 'kurumsal', 'Laboratuvarlar', 9),
('SAĞLIK', 'kurumsal', 'Ambulans Hizmetleri', 10),
('EĞİTİM', 'kurumsal', 'Üniversiteler', 1),
('EĞİTİM', 'kurumsal', 'Özel Okullar', 2),
('EĞİTİM', 'kurumsal', 'Dershaneler', 3),
('EĞİTİM', 'kurumsal', 'Kurslar ve Eğitim Merkezleri', 4),
('EĞİTİM', 'kurumsal', 'Dil Okulları', 5),
('EĞİTİM', 'kurumsal', 'Sürücü Kursları', 6),
('EĞİTİM', 'kurumsal', 'Meslek Edindirme Kursları', 7),
('EĞİTİM', 'kurumsal', 'Online Eğitim Platformları', 8),
('FİNANS', 'kurumsal', 'Bankalar', 1),
('FİNANS', 'kurumsal', 'Sigorta Şirketleri', 2),
('FİNANS', 'kurumsal', 'Finansal Danışmanlık', 3),
('FİNANS', 'kurumsal', 'Yatırım Şirketleri', 4),
('FİNANS', 'kurumsal', 'Döviz Büroları', 5),
('FİNANS', 'kurumsal', 'Faktoring Şirketleri', 6),
('FİNANS', 'kurumsal', 'Leasing Firmaları', 7),
('İNŞAAT & GAYRİMENKUL', 'kurumsal', 'İnşaat Firmaları', 1),
('İNŞAAT & GAYRİMENKUL', 'kurumsal', 'Gayrimenkul Yatırım Ortaklıkları (GYO)', 2),
('İNŞAAT & GAYRİMENKUL', 'kurumsal', 'Emlak Ofisleri', 3),
('İNŞAAT & GAYRİMENKUL', 'kurumsal', 'Proje Yönetimi', 4),
('İNŞAAT & GAYRİMENKUL', 'kurumsal', 'Mimarlık Büroları', 5),
('İNŞAAT & GAYRİMENKUL', 'kurumsal', 'İç Mimarlık', 6),
('İNŞAAT & GAYRİMENKUL', 'kurumsal', 'Dekorasyon Firmaları', 7),
('TEKNOLOJİ', 'kurumsal', 'Yazılım Şirketleri', 1),
('TEKNOLOJİ', 'kurumsal', 'Donanım Firmaları', 2),
('TEKNOLOJİ', 'kurumsal', 'Bilişim Danışmanlığı', 3),
('TEKNOLOJİ', 'kurumsal', 'Bulut Hizmet Sağlayıcıları', 4),
('TEKNOLOJİ', 'kurumsal', 'Siber Güvenlik', 5),
('TEKNOLOJİ', 'kurumsal', 'Yapay Zeka ve Makine Öğrenimi', 6),
('TEKNOLOJİ', 'kurumsal', 'E-ticaret Platformları', 7),
('TEKNOLOJİ', 'kurumsal', 'Mobil Uygulama Geliştirme', 8),
('OTOMOTİV', 'kurumsal', 'Yetkili Servisler', 1),
('OTOMOTİV', 'kurumsal', 'Otomotiv Yan Sanayi', 2),
('OTOMOTİV', 'kurumsal', 'Araç Kiralama', 3),
('OTOMOTİV', 'kurumsal', 'Filo Yönetimi', 4),
('OTOMOTİV', 'kurumsal', 'Lastik Bayileri', 5),
('OTOMOTİV', 'kurumsal', 'Yedek Parça Tedarikçileri', 6),
('OTOMOTİV', 'kurumsal', 'Araç Ekspertiz', 7),
('TURİZM & KONAKLAMA', 'kurumsal', 'Oteller', 1),
('TURİZM & KONAKLAMA', 'kurumsal', 'Tatil Köyleri', 2),
('TURİZM & KONAKLAMA', 'kurumsal', 'Butik Oteller', 3),
('TURİZM & KONAKLAMA', 'kurumsal', 'Pansiyonlar', 4),
('TURİZM & KONAKLAMA', 'kurumsal', 'Seyahat Acenteleri', 5),
('TURİZM & KONAKLAMA', 'kurumsal', 'Tur Operatörleri', 6),
('TURİZM & KONAKLAMA', 'kurumsal', 'Havayolu Firmaları', 7),
('TURİZM & KONAKLAMA', 'kurumsal', 'Rent a Car', 8),
('GIDA & İÇECEK', 'kurumsal', 'Restoran Zincirleri', 1),
('GIDA & İÇECEK', 'kurumsal', 'Gıda Üretim Tesisleri', 2),
('GIDA & İÇECEK', 'kurumsal', 'İçecek Üreticileri', 3),
('GIDA & İÇECEK', 'kurumsal', 'Catering Firmaları', 4),
('GIDA & İÇECEK', 'kurumsal', 'Toptan Gıda', 5),
('GIDA & İÇECEK', 'kurumsal', 'Organik Ürün Üreticileri', 6),
('LOJİSTİK & NAKLİYE', 'kurumsal', 'Kargo Firmaları', 1),
('LOJİSTİK & NAKLİYE', 'kurumsal', 'Nakliyat Şirketleri', 2),
('LOJİSTİK & NAKLİYE', 'kurumsal', 'Depolama Hizmetleri', 3),
('LOJİSTİK & NAKLİYE', 'kurumsal', 'Soğuk Zincir Lojistik', 4),
('LOJİSTİK & NAKLİYE', 'kurumsal', 'Uluslararası Taşımacılık', 5),
('LOJİSTİK & NAKLİYE', 'kurumsal', 'Gümrük Müşavirliği', 6),
('MEDYA & İLETİŞİM', 'kurumsal', 'Reklam Ajansları', 1),
('MEDYA & İLETİŞİM', 'kurumsal', 'Prodüksiyon Şirketleri', 2),
('MEDYA & İLETİŞİM', 'kurumsal', 'Basım ve Yayın', 3),
('MEDYA & İLETİŞİM', 'kurumsal', 'Dijital Pazarlama', 4),
('MEDYA & İLETİŞİM', 'kurumsal', 'Halkla İlişkiler', 5),
('MEDYA & İLETİŞİM', 'kurumsal', 'Sosyal Medya Yönetimi', 6),
('ENERJİ', 'kurumsal', 'Elektrik Üretimi', 1),
('ENERJİ', 'kurumsal', 'Yenilenebilir Enerji', 2),
('ENERJİ', 'kurumsal', 'Doğalgaz Dağıtımı', 3),
('ENERJİ', 'kurumsal', 'Petrol Ürünleri', 4),
('ENERJİ', 'kurumsal', 'Enerji Danışmanlığı', 5),
('ENERJİ', 'kurumsal', 'Güneş Enerjisi Sistemleri', 6),
('HUKUK & DANIŞMANLIK', 'kurumsal', 'Hukuk Büroları', 1),
('HUKUK & DANIŞMANLIK', 'kurumsal', 'Mali Müşavirlik', 2),
('HUKUK & DANIŞMANLIK', 'kurumsal', 'Vergi Danışmanlığı', 3),
('HUKUK & DANIŞMANLIK', 'kurumsal', 'İnsan Kaynakları Danışmanlığı', 4),
('HUKUK & DANIŞMANLIK', 'kurumsal', 'Yönetim Danışmanlığı', 5),
('HUKUK & DANIŞMANLIK', 'kurumsal', 'Patent ve Marka', 6)
) as v(ana, tip, alt, sira)
join public.firma_kategorileri a on a.ad = v.ana and a.tip = v.tip and a.ust_kategori_id is null;
