-- Puanlama 2. aşama: firma yanıtı, yorum şikâyetleri, panel içi yeni yorum bildirimi.

-- 1) Firma yanıtı: her yoruma firma sahibinin tek bir yanıtı (yorumlar satırında tutulur;
--    yorumlar tablosu zaten açık anahtarla okunamıyor)
alter table public.yorumlar
  add column if not exists cevap text,
  add column if not exists cevap_tarihi timestamptz,
  add column if not exists cevap_guncelleme_tarihi timestamptz,
  add column if not exists cevap_gizli boolean not null default false,   -- yönetici gizlediyse sitede görünmez
  add constraint yorumlar_cevap_uzunluk check (cevap is null or char_length(cevap) between 2 and 1000);

-- 2) Yorum şikâyetleri: aynı kişi aynı yorumu bir kez şikâyet edebilir
create table public.yorum_sikayetleri (
  id bigint generated by default as identity primary key,
  yorum_id bigint not null references public.yorumlar(id) on delete cascade,  -- yorum silinince şikâyetleri de silinir
  sikayet_eden_email text not null,
  sebep text not null check (sebep in ('hakaret', 'yaniltici', 'kisisel_bilgi', 'reklam', 'konu_disi', 'diger')),
  aciklama text check (aciklama is null or char_length(aciklama) <= 500),
  durum text not null default 'bekliyor' check (durum in ('bekliyor', 'gizlendi', 'reddedildi')),
  created_at timestamptz not null default now(),
  karar_tarihi timestamptz,
  unique (yorum_id, sikayet_eden_email)
);
create index yorum_sikayetleri_bekleyen_idx on public.yorum_sikayetleri (yorum_id) where durum = 'bekliyor';

-- 3) Panel içi bildirim: kişinin yorumlara en son ne zaman baktığı (yönetici ve firma sahibi ayrı tutulur)
create table public.yorum_bildirim_gorulme (
  kullanici_email text not null,
  kapsam text not null check (kapsam in ('yonetici', 'sahip')),
  son_gorulme timestamptz not null default now(),
  primary key (kullanici_email, kapsam)
);
create index if not exists yorumlar_created_at_idx on public.yorumlar (created_at);

-- 4) Yeni tablolarda RLS açık, politika yok; açık anahtarla okunamaz/yazılamaz (e-postalar dışarı çıkmaz).
--    Tüm okuma/yazma sunucuda yetki kontrolüyle yapılır.
alter table public.yorum_sikayetleri enable row level security;
alter table public.yorum_bildirim_gorulme enable row level security;
revoke all on public.yorum_sikayetleri from anon, authenticated;
revoke all on public.yorum_bildirim_gorulme from anon, authenticated;
